spring.application.name=ledgerline

spring.datasource.url=jdbc:postgresql://localhost:5432/ledgerline
spring.datasource.username=ledgerline
spring.datasource.password=ledgerline

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.kafka.bootstrap-servers=localhost:9092

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
