package com.ledgerline.cli;

import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import com.ledgerline.reconciliation.ReconciliationService;

/**
 * Runs reconciliation over every settlement batch that has never had a
 * {@code recon_runs} row at all, then exits.
 *
 * The Day 8 CronJob entrypoint: {@code ReconciliationService.run(batchId)}
 * needs a batch id, but a settlement batch's id is generated by {@code
 * SettlementSimulator} at file-generation time, not something a periodic job
 * can invent or is told in advance -- a real deployment's recon cadence is
 * "whatever came off the network since last time", not "reconcile this one
 * named batch". This command discovers that set itself: any {@code
 * recon_batches} row with no matching {@code recon_runs} row is unreconciled
 * and gets processed.
 *
 * Idempotent by the same mechanism {@code ReconciliationService.run} already
 * provides -- {@code resolveOrCreateRun}'s {@code ON CONFLICT DO NOTHING} --
 * so a redundant run this command's own discovery query lets slip through
 * (a batch that got a run between the query and this command reaching it)
 * costs nothing beyond a no-op.
 *
 * Reads {@code recon_batches}/{@code recon_runs} via the default,
 * application-privileged {@code JdbcTemplate} for the discovery query only
 * -- both tables live in {@code public}, and this is exactly the same
 * privilege level {@code FaultLedger}/other generator-side writers already
 * use. {@link ReconciliationService} itself still runs its own classification
 * work as {@code recon_role}, unchanged -- this command only decides *which*
 * batch ids to hand it, never how they get classified.
 *
 * Usage:
 *   --spring.profiles.active=recon [--window-seconds=86400]
 */
@Component
@Profile("recon")
public class ReconciliationRunCommand implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(ReconciliationRunCommand.class);

    private final ReconciliationService reconciliationService;
    private final JdbcTemplate jdbc;
    private final ApplicationContext context;

    ReconciliationRunCommand(
            ReconciliationService reconciliationService,
            @Autowired JdbcTemplate jdbc,
            ApplicationContext context) {
        this.reconciliationService = reconciliationService;
        this.jdbc = jdbc;
        this.context = context;
    }

    @Override
    public void run(ApplicationArguments args) throws Exception {
        int windowSeconds = Integer.parseInt(
                optional(args, "window-seconds").orElse(String.valueOf(ReconciliationService.DEFAULT_WINDOW_SECONDS)));

        List<String> unreconciled = jdbc.queryForList(
                "SELECT b.batch_id FROM recon_batches b "
                        + "WHERE NOT EXISTS (SELECT 1 FROM recon_runs r WHERE r.batch_id = b.batch_id) "
                        + "ORDER BY b.generated_at",
                String.class);

        log.info("Reconciliation run starting: {} unreconciled batch(es), windowSeconds={}",
                unreconciled.size(), windowSeconds);

        int failures = 0;
        for (String batchId : unreconciled) {
            try {
                reconciliationService.run(batchId, windowSeconds);
                log.info("Reconciled batch {}", batchId);
            } catch (Exception e) {
                // One bad batch (e.g. malformed data from a prior failed
                // generator run) must not stop every other batch behind it
                // in this run -- same reasoning TransactionConsumer applies
                // to a poison message on the topic.
                failures++;
                log.error("Failed to reconcile batch {}: {}", batchId, e.getMessage(), e);
            }
        }

        log.info("Reconciliation run complete: {} succeeded, {} failed", unreconciled.size() - failures, failures);

        // A CronJob's success/failure is read from the container's exit
        // code, so a failed batch has to surface there, not just in the
        // log -- a CronJob that always exits 0 regardless of what happened
        // is invisible to `kubectl get jobs` and any alerting built on it.
        int exitCode = failures == 0 ? 0 : 1;
        SpringApplication.exit(context, () -> exitCode);
    }

    private static Optional<String> optional(ApplicationArguments args, String name) {
        List<String> values = args.getOptionValues(name);
        return values == null || values.isEmpty()
                ? Optional.empty()
                : Optional.of(values.get(0));
    }
}
